#======================================================
# This section defines what modules are enabled at start
# by default all modules are disabled but they can be
# enabled either in game or here from the start
#
# true = Enabled from start
# false = Disabled from start
modules:
    TestModule: false
    DeathCharge: false
    DeathBan: false
#======================================================

#======================================================
# This section indicates whether or not you would like
# to keep your old configs when you update a module.
#
# true = keep
# false = do not keep
KeepOldConfigs: true
#======================================================

#======================================================
#Do not touch this variable it is used to check if your
#config needs updating by the plugin
version: 1.0
#======================================================